### ISSUE TITLE
iOS has allready set crossOrigin = 'Anonymous',still throw error 'the operation is insecure'

### ISSUE THREAD

**Issue by dengpeida** [yugasun/qrcode-decoder#14]
#### to fix this problem 
<img width="370" alt="image" src="https://user-images.githubusercontent.com/26621447/117962069-66010d80-b351-11eb-9763-a79f1d18c7b1.png">

**Comment by dengpeida** [comment]
在iOS端使用时，即使设置了crossOrigin，图片跨域依然报错，需要在给src赋值之前先set crossOrigin

**Comment by yugasun** [comment]
@dengpeida 感谢提交issue，可以帮忙提交一个 PR 来修复这个问题吗？
