### ISSUE TITLE
二维码不能识别

### ISSUE THREAD

**Issue by EastemChen** [yugasun/qrcode-decoder#15]
![image](https://user-images.githubusercontent.com/19586337/118693612-cb676980-b83d-11eb-975b-f0ab6b6a86f9.png)
为什么这个二维码不能解析啊?

**Comment by yugasun** [comment]
二维码无法识别有很多原因。比如定位点不匹配识别模式、信息点颜色对比不够、遮挡部分太大。建议尝试调整容错率、颜色、图标大小等参数并在各种二维码扫描器中测试，以保证二维码被识别的成功率
