### ISSUE TITLE
qrcode_decoder__WEBPACK_IMPORTED_MODULE_0___default.a is not a constructor

### ISSUE THREAD

**Issue by karlkidd** [yugasun/qrcode-decoder#20]
// "qrcode-decoder": "^0.3.1",
import QrCode from 'qrcode-decoder'
console.log( QrCode );
//  QrCode is {}
const qr = new QrCode();
console.log(qr);
// qrcode_decoder__WEBPACK_IMPORTED_MODULE_0___default.a is not a constructor

// this import is can be use
import QrCode  from '../node_modules/qrcode-decoder/dist/index'

// Please repair as soon as possible,thanks

**Comment by yugasun** [comment]
Can you provite reproduce project? You can find entry for different environment in https://github.com/yugasun/qrcode-decoder/blob/master/package.json#L5

**Comment by svegan** [comment]
@karlkidd have you found how to solve it? Have exactly same issue =/

**Comment by yugasun** [comment]
@svegan Could you provite repo link?

**Comment by karlkidd** [comment]
> 



> @karlkidd你找到解决方法了吗？有完全相同的问题=/

import QrCode from '../node_modules/qrcode-decoder/dist/index'

**Comment by karlkidd** [comment]
> @karlkidd have you found how to solve it? Have exactly same issue =/
// copy the node_modules/qrcode-decoder/dist/index.js file into your project
import QrCode from '../node_modules/qrcode-decoder/dist/index'

**Comment by karlkidd** [comment]
> Can you provite reproduce project? You can find entry for different environment in https://github.com/yugasun/qrcode-decoder/blob/master/package.json#L5

vue项目，不能直接import QrCode from 'qrcode-decoder'使用，但是可以这么用  import QrCode from '../node_modules/qrcode-decoder/dist/index'

**Comment by svegan** [comment]
> @svegan Could you provite repo link?

@yugasun Unfortunately no, it's private client's project.

**Comment by svegan** [comment]
> > Can you provite reproduce project? You can find entry for different environment in https://github.com/yugasun/qrcode-decoder/blob/master/package.json#L5
> 
> vue项目，不能直接import QrCode from 'qrcode-decoder'使用，但是可以这么用 import QrCode from '../node_modules/qrcode-decoder/dist/index'

Thanks @karlkidd. Thought you found some elegant solution. Your way didn't work for me anyways 😒

**Comment by yugasun** [comment]
> > @svegan Could you provite repo link?
> 
> @yugasun Unfortunately no, it's private client's project.

You can provite a reproduce demo

**Comment by sondt2709** [comment]
I'm getting same issue with nextjs
