### ISSUE TITLE
Use Rear Camera in Mobile Device

### ISSUE THREAD

**Issue by incredible888** [yugasun/qrcode-decoder#6]
Hi,

May i know how to use rear camara to decode QR.

Currently i only manage to use front camera as default.

Below is my code:

```
 let qr = new QrcodeDecoder();
  setTimeout(() => {
            try {
                var videoElem = document.querySelector("video");
                qr.decodeFromCamera(videoElem).then((res) => {
                    console.log(res);
                    if (res['data']) {
                        qr.stop();
                    }
                });
            } catch (error) {
                alert(error);
            }
        }, 200);

```

**Comment by incredible888** [comment]
Update:

Try to modify in

node-modules/qrcode-decoder/dist/index.js.  line 37
node-modules/qrcode-decoder/dist/index.esm.js. line 33
node-modules/qrcode-decoder/dist/index.aio.min.js
node-modules/qrcode-decoder/dist/index.aio.js 16724

`        this.videoConstraints = { video: true, audio: false, facingMode: 'environment' };
`

still failed to use back camera.

**Comment by yittoo** [comment]
bump. I'm having this issue aswell

**Comment by yugasun** [comment]
Latest version support use `rear camera` now, refer to https://github.com/yugasun/qrcode-decoder/commit/7d77236fc02b8bcf665fb8dc7f57e9f0543ceb38
